# Generated by Django 4.2.5 on 2023-12-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_password_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_vocabulary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
