# Generated by Django 4.2.5 on 2023-12-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_user_avatar_alter_user_user_vocabulary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
